import javax.swing.JOptionPane;
import java.awt.Toolkit;
import javax.tools.Tool;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shrabosty
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        Background = new javax.swing.JPanel();
        GameName = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        GetName = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        GetPass = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(0, 0, 0));

        Background.setBackground(new java.awt.Color(0, 0, 0));
        Background.setForeground(new java.awt.Color(0, 153, 153));
        Background.setLayout(null);

        GameName.setEditable(false);
        GameName.setBackground(new java.awt.Color(204, 204, 204));
        GameName.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        GameName.setText("       KillAssin");
        Background.add(GameName);
        GameName.setBounds(416, 23, 238, 38);

        Username.setBackground(new java.awt.Color(245, 244, 244));
        Username.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        Username.setForeground(new java.awt.Color(204, 204, 204));
        Username.setText("Username:");
        Background.add(Username);
        Username.setBounds(323, 103, 92, 24);
        Background.add(GetName);
        GetName.setBounds(419, 105, 270, 30);

        Password.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(204, 204, 204));
        Password.setText("Password:");
        Background.add(Password);
        Password.setBounds(323, 156, 82, 23);
        Background.add(GetPass);
        GetPass.setBounds(419, 157, 270, 30);

        LoginButton.setBackground(new java.awt.Color(153, 153, 153));
        LoginButton.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        LoginButton.setText("Log In");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        Background.add(LoginButton);
        LoginButton.setBounds(515, 219, 75, 25);

        SignUpButton.setBackground(new java.awt.Color(153, 153, 153));
        SignUpButton.setFont(new java.awt.Font("Algerian", 1, 11)); // NOI18N
        SignUpButton.setText("Sign Up");
        Background.add(SignUpButton);
        SignUpButton.setBounds(540, 280, 107, 23);

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("          Don't have an account?");
        Background.add(jLabel2);
        jLabel2.setBounds(323, 283, 220, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/abstract_black_red_sign_hd-wallpapers-1080p-abstract-red.jpg"))); // NOI18N
        Background.add(jLabel3);
        jLabel3.setBounds(0, 0, 760, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
 String name= GetName.getText().toString();
        char[] pass;
        pass=GetPass.getPassword();
        String password=new String(pass);
        String rname="Shrabosty";
        String rpass="1235813";
        if(name.equals(rname) && password.equals(rpass)){
        setVisible(false);
        Welcome w = new Welcome();
        w.setVisible(true);
        //w.display();
        }
        else{
            JOptionPane.showMessageDialog(null, "Wrong Username or Password", "Log In Failed!!!",JOptionPane.INFORMATION_MESSAGE);
            GetName.setText("");
            GetPass.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed
private void GetNameActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JTextField GameName;
    private javax.swing.JTextField GetName;
    private javax.swing.JPasswordField GetPass;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Password;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("assassin.png")));
    }
}
